<?php
use Laminas\Form\Form;

/** @var $form Form */
$attributes = $form->getAttributes();
if (!isset($attributes['name'])) {
    $form->setAttribute('name', 'paymentForm');
}
?>
<?php $form->prepare(); ?>
<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formCollection($form); ?>
<noscript>
    <p>Click the button below, in order to continue.</p>
    <input type="submit" class="btn btn-primary" value="Continue"/>
</noscript>
<?php echo $this->form()->closeTag($form); ?>
<script type="text/javascript">
    function clickCpmsButton() {
        document.getElementById('<?php echo $form->getAttributes()['name']; ?>').submit();
    }
    clickCpmsButton();
</script>
